In [ ]:
import sys
sys.path.append('..')

from utils.data_utils import load_dense_model_ds
from utils.train import dense_model

# load data
x_train, y_train, x_val, y_val, x_test, y_test = load_dense_model_ds()

# init and train
model = dense_model(learning_rate=1e-3, epochs=20)
model.fit(x_train, y_train, x_val, y_val)

# evaluate on test set
from utils.evaluate import accuracy, confusion_matrix
yhat = model.predict(x_test)
print(f"Test accuracy: {accuracy(yhat, y_test):.4f}")
print(confusion_matrix(yhat, y_test))

In [3]:
x_train_dm, y_train, x_val, y_val, x_test_dm, y_test = load_dense_model_ds() 
# x_train_cnn, y_train, x_test_cnn, y_test = load_cnn_model_ds() 

In [5]:
print(y_train.flatten()) 

[6 8 8 ... 9 3 1]


In [16]:
m = x_train_dm.shape[1] 
order = np.arange(0, m) 
shuffled = np.random.permutation(order) 
x = x_train_dm[:, shuffled] 
split = int(0.8 * m) 
x_train = x[:, :split]
print(x_train.shape) 

(784, 48000)


In [20]:
fashion_mnist_ds = load_dataset("zalando-datasets/fashion_mnist")

x = np.array(fashion_mnist_ds['train']['image'])
print(x.shape) 

(60000, 28, 28)


In [4]:
linear_params = init_linear_params() 
cache, A4 = forward_prop(linear_params, x_train_dm) 
print(A4) 

[[9.36307086e-122 1.75597672e-146 3.53360390e-227 ... 1.07573712e-116
  2.40369766e-110 7.65504950e-078]
 [1.00000000e+000 1.75713684e-007 2.77381863e-064 ... 9.99028767e-083
  8.34546709e-041 6.57893720e-023]
 [9.64448180e-033 9.99999824e-001 1.00000000e+000 ... 4.59102219e-031
  5.22293810e-001 1.02036750e-008]
 ...
 [6.87182420e-165 2.20054558e-167 7.66804697e-235 ... 5.44733970e-130
  4.95516794e-093 2.16497726e-039]
 [5.83376331e-151 2.27784847e-137 5.15631090e-165 ... 6.29175659e-077
  5.51448251e-057 8.60565404e-048]
 [7.34327636e-030 3.08346688e-109 7.93859958e-183 ... 1.37782317e-101
  7.60365494e-084 3.05362983e-046]]


In [6]:
import numpy as np 
z = np.random.randn(50, 100)
A = np.random.rand(*z.shape) < 0.8
z = z * A / 0.8
print(z) 

[[ 0.          1.94952225  1.54977641 ... -0.90555143 -2.84129127
  -0.        ]
 [-0.         -0.         -2.5552416  ...  0.41502328  0.31064582
  -0.42060729]
 [ 1.94089579  1.88384415  2.43066789 ...  1.4477668   0.
   0.        ]
 ...
 [ 2.9796305  -1.30888818  0.         ...  1.70553071 -0.
  -0.88814244]
 [ 0.1578492   0.          0.69566686 ... -1.86132358  0.02925398
  -0.04385302]
 [ 0.28820315  0.54667425 -0.87950738 ... -1.12438197  0.
   0.        ]]


In [17]:
x = np.arange(0, x_train_dm.shape[1]) 
x = np.random.permutation(x) 
x_train_dm = x_train_dm[:, x]
print(x_train_dm) 

[[-0.81025766  0.18950704  0.47832795 ... -0.81025766  2.02240898
   1.01153579]
 [-0.81025766  2.02240898 -0.05487989 ...  0.22283253  0.47832795
  -0.78804066]
 [-0.81025766  0.62273841 -0.81025766 ... -0.81025766 -0.81025766
   1.76691356]
 ...
 [ 1.35589918  1.58917761 -0.81025766 ... -0.81025766  2.02240898
  -0.81025766]
 [ 0.90045082 -0.3325923   0.71160638 ... -0.81025766 -0.81025766
  -0.81025766]
 [ 0.91155932 -0.81025766  1.35589918 ... -0.81025766  1.57806912
  -0.81025766]]


In [58]:
def confusion_matrix(yhat: np.ndarray, y: np.ndarray, n_classes: int = 10):
    """
        yhat: (1, m) predicted class indices
        y:    (1, m) true class indices
        Return:
            confusion_matrix: (n_classes, n_classes)
            Diagonal     -- correct predictions
            Off-diagonal -- mistakes
    """
    cm = np.zeros((n_classes, n_classes), dtype=int)
    for true, pred in zip(y.flatten(), yhat.flatten()):
        cm[true][pred] += 1
    return cm

matrix = confusion_matrix(yhat, y) 
print(matrix) 

[[ 2 15 15 16 14 13  8 11 19 10]
 [ 6 11  2  9  5 12  9  5 11  8]
 [12 18 15  5 12  7 11 12  9 12]
 [10  4  5 16 11 15 10 12  2  8]
 [ 7  9  8 12 14 11  8  8  9  9]
 [12 11 10 16 14 10 11 17 12  8]
 [10  8  8  4 12  6  6 12  7 11]
 [13 13  4 16  9  5  6 11 17  7]
 [15  8 11  5  5  9  5 13 11  4]
 [11  8 11  8  7 10 15 11 16  9]]
